BackendBundle\Entity\Embalaje:
    type: entity
    table: embalajes
    indexes:
        fk_embalaje_user:
            columns:
                - id_user
        fk_embalaje_order:
            columns:
                - id_order
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        guia:
            type: string
            nullable: true
            length: 120
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        state:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
    manyToOne:
        idOrder:
            targetEntity: Order
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_order:
                    referencedColumnName: id
            orphanRemoval: false
        idUser:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_user:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
