BackendBundle\Entity\Shipping:
    type: entity
    table: shipping
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        phone:
            type: string
            nullable: true
            length: 120
            options:
                fixed: false
        state:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
    lifecycleCallbacks: {  }
