shipping_new:
    path: /new
    defaults: { _controller: 'AppBundle:Shipping:new' }
    methods: POST

shipping_edit:
    path: /edit/{id}
    defaults: { _controller: 'AppBundle:Shipping:edit', id:null }
    methods: POST

shipping_list:
    path: /list
    defaults: { _controller: 'AppBundle:Shipping:list' }
    methods: POST