user_login:
    path: /login
    defaults: { _controller: 'AppBundle:User:login' }
    methods: POST

user_new:
    path: /new
    defaults: { _controller: 'AppBundle:User:new' }
    methods: POST

user_edit:
    path: /edit/{id}
    defaults: { _controller: 'AppBundle:User:edit', id:null }
    methods: POST

user_list:
    path: /list
    defaults: { _controller: 'AppBundle:User:list' }
    methods: POST

user_sellers:
    path: /seller-list
    defaults: { _controller: 'AppBundle:User:sellers' }
    methods: POST

user_upload_image:
    path: /upload-image
    defaults: { _controller: 'AppBundle:User:uploadImage' }
    methods: POST